###
GET http://localhost:9000/api/usuarios HTTP/1.1

###
POST http://localhost:9000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "usu_email": "andres.perez@o365.unab.edu.co",
    "usu_clave": "8723",
    "usu_nombres": "Andres Fernando",
    "usu_apellidos": "Perez Acosta"
}


###
DELETE http://localhost:9000/api/usuarios/usu_id/2 HTTP/1.1


###
PUT http://localhost:9000/api/usuarios/usu_id/3 HTTP/1.1
Content-Type: application/json

{
    "usu_email": "andres.perez@o365.unab.edu.co",
    "usu_clave": "8723",
    "usu_nombres": "Andres Fernando",
    "usu_apellidos": "Perez Acosta"
}


